version: '3'
services:

  es011: #API
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es011
    environment:
      - node.name=es011
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es022,es03
      - cluster.initial_master_nodes=es011,es022,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  es022: #worker1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es022
    environment:
      - node.name=es022
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es011,es03
      - cluster.initial_master_nodes=es011,es022,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  redis:
    image: "redis:alpine"

  api:
    build: ./api
    links:
      - es011
    networks:
      - elastic
    ports:
      - 80:80


volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  elastic:
    driver: bridge
